language: go

go:
  - 1.3
  - tip
install: go get -d -v ./... && go build -v ./...
script:
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls 
  - go test -v -bench . -cpu 1,2,4,8 ./... 
  - go vet -v ./...
  - docs/project-code-coverage.sh

notifications:
  email:
    - tiago.natel@neoway.com.br

